### ISSUE TITLE
How can I delete a tag?

### ISSUE THREAD

**Issue by suedroplet** [lvxianchao/the-fucking-github#10]
Nice work! But I just get something confused. When I enter a wrong tag by mistake, it's stick on my filter docker. How can I delete it???

**Comment by lvxianchao** [comment]
Are you want to remove this incorrectly entered tag from your existing tag list?

**Comment by suedroplet** [comment]
Yes！What should I do？？😭

**Comment by suedroplet** [comment]
Yes！Is any possible approach available？😭

**Comment by suedroplet** [comment]
Yes！Is any possible approach available？😭

**Comment by lvxianchao** [comment]
@suedroplet Sorry, maybe you need to wait a while, I will add this feature right away.

**Comment by suedroplet** [comment]
Oh thanks！You’re so kind.

**Comment by suedroplet** [comment]
@lvxianchao Oh thanks！You’re so kind.

**Comment by handbye** [comment]
强烈建议添加此功能，另外这个插件简直太棒了。感谢作者！👍

**Comment by lvxianchao** [comment]
@handbye 感谢你的认可，可以分享给有同样需要的小伙伴哈！功能会有的，还请稍安匆躁。

**Comment by jjeejj** [comment]
现在可以删除一个仓库的标签了 :+1:

**Comment by lvxianchao** [comment]
@suedroplet   v1.4.0 解决了这个问题
