### ISSUE TITLE
[建议]加入Download Zip功能

### ISSUE THREAD

**Issue by EatGuaa** [lvxianchao/the-fucking-github#11]

**Comment by lvxianchao** [comment]
@junkwei 兄弟，你这个需求严重跑偏啊。项目本质目的主要是解决 Star 的问题，不排除后期可能会添加。

**Comment by EatGuaa** [comment]
@lvxianchao 搜索到这个库的时候，又想直接下载下来，不想clone啊-.-。插件非常棒！
