### ISSUE TITLE
13寸下 style 有问题

### ISSUE THREAD

**Issue by zenghongtu** [lvxianchao/the-fucking-github#12]
做的很好看，赞一个！

问题如下图：
![image](https://user-images.githubusercontent.com/25629121/58849769-3e618f00-86be-11e9-943a-35192c8e9616.png)

**Comment by lvxianchao** [comment]
@zenghongtu 老兄，我在 v1.3.1 里微调了一下距离，在我的屏幕上模拟到 1220px 的时候仍可以正常显示，你可以更新一下试试，如果仍然有问题请在这里给我反馈！（Header 那里的布局写的很烂，想把 Bug 都修完再大调一下，整个代码写的都很烂 😆 ）
