### ISSUE TITLE
统计tag有bug

### ISSUE THREAD

**Issue by shooterRao** [lvxianchao/the-fucking-github#15]
https://github.com/lvxianchao/the-fucking-github/blob/master/src/js/components/Search.vue#L251
定位到这行代码逻辑问题 🤔

**Comment by shooterRao** [comment]
![image](https://user-images.githubusercontent.com/23609695/59009331-ba470d00-885f-11e9-8a43-2af9f3bdf9b8.png)

你好，如图，当我把全部项目都打了tag分类，`Untagged Repositories`选项统计应该为0

**Comment by lvxianchao** [comment]
@shooterRao 谢谢你！很棒的问题反馈！
