### ISSUE TITLE
[建议]加入将标签导出的功能

### ISSUE THREAD

**Issue by Vauke** [lvxianchao/the-fucking-github#18]
尝试了下换浏览器, 打的标签就没有了, 对于以后重装或是换浏览器不太方便呀

**Comment by lvxianchao** [comment]
@Vauke 同步只针对 Chrome 系列浏览器，不支持其它的。

**Comment by Vauke** [comment]
@lvxianchao 是的, 用的chrome beta, 我也只用chrome 哈哈

**Comment by Vauke** [comment]
我再试试?

**Comment by lvxianchao** [comment]
我昨晚测试是没有问题，昨晚在虚拟机安装了Ubuntu，你可以再试一下，如果还是有问题，请辛苦扔一个录屏，也好分析一下。

**Comment by Vauke** [comment]
感觉不用录屏, 刚试了win下的chrome也不能显示之前打过的tag, 感觉只是存在了本地
