### ISSUE TITLE
两台设备之间不能同步

### ISSUE THREAD

**Issue by MyFaith** [lvxianchao/the-fucking-github#19]
我在mac下都标记好了，然后到windows下全都是没标记的，然后回到mac，所有500多个star的标记都没了。。。。。。

**Comment by lvxianchao** [comment]
@MyFaith 额。。。抱歉，这简直是一个不可饶恕的 Bug 。。。😢

**Comment by MyFaith** [comment]
建议还是增加一下其他的存储方式吧，chrome有时候同步会丢东西。。可以放到gist，坚果云这些地方

**Comment by lvxianchao** [comment]
@MyFaith 有道理，收下了！
