### ISSUE TITLE
怎么给仓库打标签???...

### ISSUE THREAD

**Issue by MichaelPorter0** [lvxianchao/the-fucking-github#20]
恩..这个问题好像有的low,但我确不知道怎么打标签..

**Comment by lvxianchao** [comment]
![image](https://user-images.githubusercontent.com/22412818/59784489-1fd1d980-92f5-11e9-911d-0623001296ec.png)

直接输入，或者选择。

**Comment by MichaelPorter0** [comment]
哦哦哦 谢谢,原来这有个输入框..
