### ISSUE TITLE
Unable to load data

### ISSUE THREAD

**Issue by owen800q** [lvxianchao/the-fucking-github#21]
Taking nearly 26 minutes so far, but nothing are loaded ....
![image](https://user-images.githubusercontent.com/19252045/60392774-13dbe800-9b3d-11e9-8aab-79f34b58ae5b.png)

**Comment by lvxianchao** [comment]
Star 的数量过多，导致频繁请求 Github 的 API 受到限制了，这个问题目前还没有找到好的解决办法。
