### ISSUE TITLE
关于新的版本暂时无法发布。

### ISSUE THREAD

**Issue by lvxianchao** [lvxianchao/the-fucking-github#25]
最新版本 1.14.0 于 2019 年 06 月 23 号提交应用商店，但至今为止状态仍然是待审核状态，原因不明。

扩展处于此状态下，我无法发布更新或修改。

**Comment by zhiweio** [comment]
等你

**Comment by zhiweio** [comment]
先 star

**Comment by lvxianchao** [comment]
距离上个版本上传商店已经过去半个多月了，插件仍然处于**待审核**状态中，已再次联系 Google，尚未得到结果。

![image](https://user-images.githubusercontent.com/22412818/60868396-88aad280-a25f-11e9-8d2b-c0f382c49a8d.png)

**Comment by d0gkiller87** [comment]
兄弟不觉得是关键字的问题吗哈哈~

**Comment by ghost** [comment]
要不要换一个关键字吧，fucking这个词不太好吧

**Comment by lvxianchao** [comment]
@vungsung @HaleWangTechHub 感谢二位，目前判断问题应该是出在名称上，后续调整后会重新上架。

**Comment by mingxv** [comment]
还没解决么

**Comment by chiperman** [comment]
现在有消息了吗？

**Comment by d0gkiller87** [comment]
看來只能自己打包安裝了

**Comment by FlyMeToTheMars** [comment]
> 看來只能自己打包安裝了

兄弟这个是怎么打包的啊，对这块没有接触

**Comment by d0gkiller87** [comment]
很簡單的，Baidu 搜 Load unpacked extension
至於Chrome會在每次重啟瀏覽器都將開發者插件停用，用組策略編輯器(Windows pro以上)+Chrome範本+自己打包好的插件+將其ID加入白名單就行了，自己寫的插件沒錢發佈到商店也都這樣搞，這部分有點複雜，網上教程很零碎，我自己看國外論壇摸索的，改天再寫個教程

**Comment by chiperman** [comment]
> 很簡單的，Baidu 搜 Load unpacked extension
> 至於Chrome會在每次重啟瀏覽器都將開發者插件停用，用組策略編輯器(Windows pro以上)+Chrome範本+自己打包好的插件+將其ID加入白名單就行了，自己寫的插件沒錢發佈到商店也都這樣搞，這部分有點複雜，網上教程很零碎，我自己看國外論壇摸索的，改天在寫個教程，現在如果有問題可以加我QQ212880454

兄弟有博客链接吗？能不能麻烦写好在这里发一下链接？

**Comment by d0gkiller87** [comment]
你們可以先加載未打包版本來試用插件功能，我找到一個寫很清楚的: https://github.com/kuleyu/IFE-Tasks/issues/1
差別在於，當你結束了Chrome的進程，重新打開時Chrome會提示已自動禁用該插件，但這種情況只存在於真的想繼續使用該插件，若你們試完還真的想做持久安裝，再麻煩告訴我，不然我還有一堆逆向工程的專題要做，若文章寫了沒人用真的白費力氣。

**Comment by hxverygood** [comment]
改名了仍然无法通过审核吗？

**Comment by ddzy** [comment]
`The fucking github` 商店搜不到了, 新的名称是什么呢?
