### ISSUE TITLE
搜索已star项目后，项目列表无法向下滑动

### ISSUE THREAD

**Issue by cnyy99** [lvxianchao/the-fucking-github#5]
环境：
- win10
- chrome 版本 73.0.3683.103（正式版本） （64 位）

**Comment by lvxianchao** [comment]
通过什么条件搜索的？可以描述的更详细一些吗？

**Comment by lvxianchao** [comment]
@cnyy7 嗨，请问你是通过什么条件搜索的？可以描述更详细一些吗？

**Comment by lvxianchao** [comment]
@cnyy7 我这边测试搜索 Untagged 的项目是可以滚动的，不知道你那里具体什么情况？可否描述得更详细一些呢？

**Comment by cnyy99** [comment]
@lvxianchao   [演示视频](https://mega.nz/#!Or5AnQ7b!Bmih80hKFvGLbMAibKfy88ymWUx1hMFSQTchUAacet0)
我录了一个视频演示，我搜索vue时的展示，显示有8个结果，但第四个只能看到一点就滑不下去了。
后来试了其他关键词，搜索go有17个结果，只能滑到第10个，第11个只能看到一部分，然后就滑不下去了。
