### ISSUE TITLE
search online 组件样式问题

### ISSUE THREAD

**Issue by xnnzh** [lvxianchao/the-fucking-github#6]
我的电脑屏幕的分辨率是 768 的。search online 组件的宽度是固定值 `400px` 导致后面的组件溢出。

**Comment by lvxianchao** [comment]
@zxbetter 哈哈，还有种这种分辨率，能截个图看看效果吗？

**Comment by xnnzh** [comment]
这是我电脑的分辨率

![image](https://user-images.githubusercontent.com/14057796/56486113-27e5e680-6509-11e9-98fc-9ded3dc3bd1e.png)

这是效果

![image](https://user-images.githubusercontent.com/14057796/56486357-e86bca00-6509-11e9-9bbb-0617a3c21bac.png)

**Comment by lvxianchao** [comment]
OK，今晚会发新版本解决这个问题。

**Comment by lvxianchao** [comment]
@zxbetter 按道理 1366 * 768 应该不至于把布局挤爆，你的浏览器窗口最大化状态吗？下面是我模拟出 1366 的分辨率。

![image](https://user-images.githubusercontent.com/22412818/56502524-289c6e00-6545-11e9-9254-bae0412abea8.png)

**Comment by xnnzh** [comment]
我的浏览器是最大化状态的呀。
![image](https://user-images.githubusercontent.com/14057796/56502993-ef64fd80-6546-11e9-9bfe-b537014e50e4.png)

**Comment by lvxianchao** [comment]
@zxbetter 奇怪了，我这到里模拟至少要小于 1330 才会挤爆呢 😢

**Comment by lvxianchao** [comment]
@zxbetter 我暂时调整一下 Search Online 组件的宽度，然后限定屏幕最小宽度为 1366，上传一个新版本明天看下效果。

**Comment by lvxianchao** [comment]
@zxbetter 已上传了新的版本，版本号为：v1.1.1 ，大约过一个小时就更新到商店。

**Comment by xnnzh** [comment]
@lvxianchao 感谢跟进，我现在看到已经修复了。
