### ISSUE TITLE
【建议】对 Tags Dropdown 的内容镜像字典排序

### ISSUE THREAD

**Issue by webup** [lvxianchao/the-fucking-github#7]
现在搜索 Tags 的下拉框里面的内容目测是按 Tag 创建时间排序的，建议优化为按字典序排列，窃以为这样找起来会方便一些。

**Comment by lvxianchao** [comment]
你是指按标签搜索项目那里吗？我平时会输入点字母以减小标签的范围。

**Comment by webup** [comment]
是的，标签比较多，会想看一下做了哪些标签，各种有多少已标记的项目。

**Comment by lvxianchao** [comment]
OK，容我考虑一下。
